# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('author_name', models.CharField(max_length=500)),
                ('publisher_name', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField(verbose_name='published at')),
                ('unit_price', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=500)),
                ('rating_count', models.IntegerField(default=0)),
                ('rating_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=2000)),
                ('commented_at', models.DateTimeField(verbose_name='commented at')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(verbose_name='ordered at')),
                ('shipping_address', models.CharField(max_length=500)),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Order')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('full_name', models.CharField(max_length=500)),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.User'),
        ),
    ]
