# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='order_id',
            new_name='order',
        ),
    ]
