# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_alter_field_is_active_to_true'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='date_of_birth',
            new_name='birthday',
        ),
    ]
